### ISSUE TITLE
Hide Dropcap Setting for Paragraphs in WordPress 5.5

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/mrw-simplified-editor-wordpress#15]
WordPress 5.5 removes the possibility of CSS trickery to hide the Drop Cap setting. 😡

**Comment by xemlock** [comment]
This may help: https://github.com/joppuyo/remove-drop-cap (at least it worked for me).

**Comment by mrwweb** [comment]
@xemlock Thanks so much for sharing this. I had not seen this before! It looks like it's still relying on the "experimental" API in the editor, but this is a big enough issue for me that it's probably worth using. I'll see about getting it into the next release.
